{% set name = "findent" %}
{% set version = "4.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/project/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c010ce4d020ec77c055e0dea1f29a2f52815cb4debe052fd559cf09049fac702
  patches:
    - man-page.patch  # [target_platform != build_platform]

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - bison
    - flex
    - autotools_clang_conda  # [win]
    - libtool   # [unix]
    - automake  # [unix]
    - autoconf  # [unix]
    - make
    - perl

test:
  commands:
    - findent --version

about:
  home: https://www.ratrabbit.nl/ratrabbit/findent/
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - COPYING
  summary: Indents/beautifies/converts Fortran sources.
  doc_url: https://sourceforge.net/p/findent/wiki/
  dev_url: https://github.com/wvermin/findent

extra:
  recipe-maintainers:
    - awvwgk
    - gnikit
