{% set name = "findent" %}
{% set version = "4.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.sourceforge.net/project/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c010ce4d020ec77c055e0dea1f29a2f52815cb4debe052fd559cf09049fac702

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - bison
    - flex
    - autoconf
    - make

test:
  commands:
    - findent --version

about:
  home: https://sourceforge.net/projects/{{ name }}/
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - COPYING
  summary: Indents/beautifies/converts Fortran sources.
  doc_url: https://sourceforge.net/p/{{ name }}/wiki/
  dev_url: https://sourceforge.net/p/{{ name }}/code/HEAD/tree/

extra:
  recipe-maintainers:
    - awvwgk
    - gnikit
